### ISSUE TITLE
Hydronet installation on Pearl

### ISSUE THREAD

**Issue by juripapay** [stfc-sciml/sciml-bench#24]
When I tried to run hydronet on Pearl I came across the following error:

sciml-bench run --mode training hydronet
The benchmark hydronet does not support training. Have you installed yet? Check with "sciml-bench list benchmarks --verify"

The "sciml-bench list benchmarks --verify" produces this list:
Benchmarks
 ----------

  * em_denoise            : Not runnable
  * dms_structure         : Not runnable
  * slstr_cloud           : Not runnable
  * optical_damage        : Not runnable
  * stemdl_classification : Not runnable
  * hydronet              : Not runnable
  * inelastic             : Not runnable
  * mnist_tf_keras        : Not runnable

**Comment by samueljackson92** [comment]
This is now working for me. Closing.
