### ISSUE TITLE
Hydronet - torchrun

### ISSUE THREAD

**Issue by juripapay** [stfc-sciml/sciml-bench#27]
The parallel version of hydronet requires the use of torchrun for running the benchmark. In the standalone version it is not a problem, however in the sciml-bench framework we need to extend the command which launches the benchmarks at least for the hydronet case by using:
python -m torch.distributed.launch application.py

If we use only python, then this command will fail:
dist.init_process_group(backend="nccl", init_method='env://')

**Comment by samueljackson92** [comment]
This has been solved as part of #29. We can use the `--no_python` command:

`torchrun --standalone --no_python --nproc_per_node=2 sciml-bench run hydronet`
