### ISSUE TITLE
slstr_cloud dataset is too big

### ISSUE THREAD

**Issue by yonatan123s** [stfc-sciml/sciml-bench#30]
hello,
I am trying to download the slstr_cloud dataset with the "sciml-bench download slstr_cloud_ds1" command but it happens to be much bigger than 180GB (currently over 700GB and still running).
Is it the right command?
Is there another way to download this dataset?

thanks in advance

**Comment by juripapay** [comment]
Please try to download the dataset now. Thanks

**Comment by yonatan123s** [comment]
It works now. Thank you
